question_data = [
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "The main character in the &quot;Half-Life&quot; franchise is named Morgan Freeman.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
          "question": "The book 1984 was published in 1949.", "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
          "question": "Ada Lovelace is often considered the first computer programmer.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Pluto is a planet.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
          "question": "Psychology is the science of behavior and mind.", "correct_answer": "True",
          "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                            "question": "Nova Scotia is on the east coast of Canada.",
                                            "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.", "correct_answer": "True",
          "incorrect_answers": ["False"]}]
